FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

COPY auth-service/src/. ./auth-service/src
COPY shared ./shared
COPY Directory.Packages.props ./

WORKDIR /src/auth-service/src

CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:80"]